package org.luiz.sa.waterdatacollector;

import org.luiz.sa.waterdatacollector.model.AverageDeviceReadValues;
import org.luiz.sa.waterdatacollector.model.DeviceReadValues;
import org.luiz.sa.waterdatacollector.model.WaterData;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.sql.SQLException;
import java.time.Instant;
import java.util.List;

@RestController
@CrossOrigin(origins = "*")
public class WaterDataCollectorController {
    @Autowired
    private WaterDataCollectorService service;

    @PostMapping("/")
    public String index() throws SQLException {
        return "Greetings from Spring Boot!";
    }

    @GetMapping("/getLastHourReadsByDeviceId") // Return an object(DeviceReadValues) with a list of each sensor data in the past hour.
    public DeviceReadValues lastHourReadingData(@RequestParam String deviceId) throws SQLException {
        return service.loadAllSensorsValuesByDeviceId(deviceId);
    }

    @GetMapping("/getLastReadData") // Return an object(WaterData) with the last data generated by the device.
    public WaterData lastReadData(@RequestParam String deviceId) throws SQLException {
        return service.loadLastReading(deviceId);
    }

    @GetMapping("/getAverageValues") //Return an object(AverageDeviceReadValues) each contains the average of each sensor data, from the past hour.
    public AverageDeviceReadValues averageValue(@RequestParam String deviceId) throws SQLException {
        return service.averageValueLastHourReads(deviceId);
    }

    @PostMapping("/postDeviceData")
    public void post() throws SQLException {
        WaterData waterData = new WaterData();
        waterData.setDeviceId("deviceId");
        waterData.setPh(5.5f);
        waterData.setTemperature(5.5f);
        waterData.setTds(55);
        waterData.setTimestamp(Instant.now().toEpochMilli());
        service.saveData(waterData);
    }

}